# SQL Server - DEV
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=lights_dev_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=YourStrong@Passw0rd
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# MongoDB - DEV
spring.data.mongodb.uri=mongodb://localhost:27017/lights_log_dev_db

# DEV devices
app.devices.count=5

