# SQL Server - QA
spring.datasource.url=jdbc:sqlserver://localhost:1434;databaseName=lights_qa_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=YourStrong@Passw0rd
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# MongoDB - QA
spring.data.mongodb.uri=mongodb://localhost:27018/lights_log_qa_db

# QA devices
app.devices.count=3

